apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart-whoami
  namespace: whoami
rules:
  - apiGroups: ["*"]
    resources: ["deployments"]
    resourceNames: ["whoami"]
    verbs: ["get", "patch", "list", "watch"] # extended list of operations
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart-whoami
  namespace: whoami
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-whoami
  namespace: whoami
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart # important - the name of the service account
    namespace: whoami
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-whoami
  namespace: whoami
spec:
  concurrencyPolicy: Forbid
  schedule: "0/15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: deployment-restart-whoami
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/whoami'